export const environment = {
  production: false,
  apiBaseUrl: 'http://127.0.0.1:5277',
  paystackPublicKey: '',
  flwPublicKey: '',
  whatsappNumber: '2348158406306',
  ga4MeasurementId: 'G-JXHLLEKVJW',
  youtubeHomeVideoId: 'dQw4w9WgXcQ',
  youtubeTechSchoolVideoId: 'dQw4w9WgXcQ',
  youtubePythonVideoId: 'dQw4w9WgXcQ',
  youtubeFrontendVideoId: 'dQw4w9WgXcQ',
  youtubeDotnetVideoId: 'dQw4w9WgXcQ',
  youtubeCloudVideoId: 'dQw4w9WgXcQ',
  youtubeDataAnalysisVideoId: 'dQw4w9WgXcQ',
};
